version: '3.6'

services:

#================================================================================================
# RVM (Ruby Verion Manager)
#================================================================================================
  rvm:
    restart: unless-stopped
    container_name: rvm_${UBUNTU_VERSION:-18.04}_${RUBY_VERSION:-2.6.6}
    build:
      context: .
      args:
        - UBUNTU_VERSION=${UBUNTU_VERSION:-18.04}
        - RUBY_VERSION=${RUBY_VERSION:-2.6.6}
    ports:
      - "${RVM_PORT:-226}:22"
    tty: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
